### ISSUE TITLE
Unable to add NFL Events (New Addition)

### ISSUE THREAD

**Issue by rh535** [m0ngr31/EPlusTV#114]
I don't have NFL+, but I do have NFL Network (Youtube TV provider), Amazon Prime and NBC Peacock. I have added the correct variables I believe. 

I don't see anything in the logs asking for anything related to the new NFL additions. I am running EPlusTV: v3.2.6 (latest) on unRAID 6.12.10 (latest stable). I have provided my NFL variables (photo).

Thank you so much

NFL Variables
![Screenshot 2024-10-06 at 08-53-46 Klauss_UpdateContainer](https://github.com/user-attachments/assets/1cb87979-5eb1-41b0-8004-70398089b70d)

Full Container Variables
![Screenshot 2024-10-06 at 08-57-40 Klauss_UpdateContainer](https://github.com/user-attachments/assets/00d80e2f-370a-41e5-b600-036e815b0f89)

**Comment by rh535** [comment]
I'm still not getting anything in the logs or any new channels. Do I need to have an NFL+ account at baseline to get the NFL network to show up? I do have it with YouTube TV. I also have a Peacock sub and an Amazon Prime sub for those variables (I just haven't seen anything in the logs asking for those yet).

**Comment by m0ngr31** [comment]
You'll need to set `NFLPLUS=true` as well. As unintuitive as it sounds. It'll just work off of an NFL account instead.

**Comment by rh535** [comment]
> You'll need to set `NFLPLUS=true` as well. As unintuitive as it sounds. It'll just work off of an NFL account instead.

This was the issue. Thanks for all your work and insights!
